version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
